max_workers: 8

storage:
  mongodb:
    uri: "mongodb://localhost:27017"
    db_name: "novelpal"
    entity_collection_name: "entities"
  neo4j:
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "12345678"
  vector_db:
    qdrant:
      host: "localhost"
      port: 6333

llm:
  model_used: 
    common: "deepseek"
    reasoner: "deepseek-r"
  qwen:
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    api_key: "sk-xxx"
    model: "qwen-plus" # 模型列表：https://help.aliyun.com/zh/model-studio/getting-started/models
  zhipu:
    base_url: "https://open.bigmodel.cn/api/paas/v4/"
    api_key: "xxx.4U2Rj5ejnV3CjPSr"
    model: "glm-4-plus" # glm-4-plus glm-4-air
  deepseek:
    base_url: "https://api.deepseek.com"
    api_key: "sk-xxx"
    model: "deepseek-chat" # deepseek-chat deepseek-reasoner
  deepseek-r:
    base_url: "https://api.deepseek.com"
    api_key: "sk-xxx"
    model: "deepseek-reasoner" # deepseek-chat deepseek-reasoner
  local:
    model_path: "/models/qwen-14b-chat"

cache:
  redis:
    enabled: true
    ttl: 3600

logging:
  level: "INFO"
  file: "logs/novelpal.log"
